version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g jest

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run test:jest

cache:
  paths:
    - './node_modules/**/*'