service: SocialJusticeWarriorsBackend

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    endpointType: REGIONAL

functions:
    main:
        handler: src/index.handler
        events:
            - http: ANY /
            - http: "ANY {proxy+}"

plugins:
    - serverless-plugin-typescript
    - serverless-express

inputs:
    src:
        src: ./src
        hook: npm run build
        dist: ./dist
    domain: thesocialjusticewarriors.com
    region: us-east-1
